# Generated by Django 3.2.4 on 2021-06-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sales', '0001_initial'),
        ('devices', '0005_auto_20210529_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_sales.pointofsale'),
        ),
    ]
