# Generated by Django 3.2.3 on 2021-05-29 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='store',
        ),
        migrations.AddField(
            model_name='device',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
