version: "3.6"
#version: "3.3"
   
services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql@12/data
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DIRECCIÓN_RED_IP_LOCAL=52.86.237.160
  #reverse_proxy:
    #image: nginx
      #volumes:
        #- ./templates:/etc/nginx/templates
      #ports:
        #- "80:80"
        #- "443:443"
      #environment:
        #- NGINX_HOST=foobar.com
        #- NGINX_PORT=80

    
